<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><i class="fa  fa-book fa-fw"></i> Документация</h1>

    </div>
    <!-- /.col-lg-12 -->
</div>	
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="data_form document_form">
                 <?php echo $this->form; ?>
                </div>

            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="dataTable_wrapper">
                    <table width=100% class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                            <tr>
                                <th>Название&nbsp<a class="fa fa-sort fa-fw" href="<?php echo $this->url(array(), 'catalog_sort_name'); ?>"></a></th>                  
                                <th>Имя файла</th>
                                <th><center><i class="fa fa-folder-open-o fa-fw"></i></center></th>
                                <th><center><i class="fa fa-trash-o fa-fw"></i></center></th>
                            </tr>
                        </thead>
                        <tbody>

                            <?php
                            foreach ($this->data as $rows) {
                                ?> <tr class="gradeA">
                                    <td><?= $this->escape($rows['description']) ?></td>
                                    <td><?= $this->escape($rows['path']) ?></td>
                            <td><center><a class="fa fa-folder-open-o fa-fw" href="/data/<?= $this->escape($rows['path']) ?>"></a></center></td>
                            <td><center><a class="fa fa-trash-o fa-fw" href="/documentation/delete/name/<?= $this->escape($rows['path']) ?>/id/<?= $this->escape($rows['id']) ?>"></a></center></td>
                            </tr> <? } ?>                            

                        </tbody>
                    </table>
                </div>
             </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>

