<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header" id='test_js'><i class="fa fa-edit fa-fw"></i> Склад запчастей</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>	
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <table width=100% border="0">
                   <tr  align="left">
                    <td width="20%" align="left">
                        <div class="dataTables_length" id="dataTables-example_length">
                            <form id="form_select" name="form_select" method="post">
                                Показать 

                                <select name="select_limit" onchange="form_select.submit();">
                                    <option <? if($_SESSION['select_limit']== 10) {echo('selected ');} ?>value="10">10</option>
                                    <option <? if($_SESSION['select_limit']== 25) {echo('selected ');} ?>value="25">25</option>
                                    <option <? if($_SESSION['select_limit']== 50) {echo('selected ');} ?>value="50">50</option>
                                    <option <? if($_SESSION['select_limit']== 100) {echo('selected ');} ?>value="100">100</option>
                                </select>
                                
                                <input name="search_catalog" type="hidden" value="<?=$this->search?>" >

                             </form>
                        </div>
                    </td>
                   <td align="left">
                        <div class="dataTables_length" id="dataTables-example_length">
                            <button type="button" onclick="window.location.href = '/warehouse/load/'" class="btn btn-default">Загрузка</button>
                            <button type="button" onclick="window.location.href = '/warehouse/unload/'" class="btn btn-default">Выдача</button>
                            <button type="button" onclick="window.location.href = '/warehouse/add/'" class="btn btn-default">Добавить</button>
                            <button type="button" onclick="window.location.href = '/warehouse/index/page/1'" class="btn btn-default">Обновить</button>
                            <button type="button" onclick="window.location.href = '/warehouse/history/'" class="btn btn-default">История</button>
                            <button type="button" onclick="window.location.href = '/warehouse/toexcel/'" class="btn btn-default">ToExcel</button>
                        </div>
                    </td>
                    <td  width="20%" align="right">
                        <div class="dataTables_length" id="dataTables-example_length">
                            <form id="search_form" method="post">
                            <div class="input-group custom-search-form">
                                <input name="search_catalog" type="text" value="<?=$this->search?>" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                    <button form="search_form" class="btn btn-default" type="submit">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                            </form>
                        </div>
                    </td>
                    </tr>
                </table>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="dataTable_wrapper">
                    <table width=100% class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                            <tr >
                                <th>Фото&nbsp<a class="fa fa-sort fa-fw" href="<?php echo $this->url(array(), 'warehouse_sort_serial'); ?>"></a></th>
                                <th>Серийный номер&nbsp<a class="fa fa-sort fa-fw" href="<?php echo $this->url(array(), 'warehouse_sort_serial'); ?>"></a></th>
                                <th>Название&nbsp<a class="fa fa-sort fa-fw" href="<?php echo $this->url(array(), 'warehouse_sort_name'); ?>"></a></th>
                                <th>Тип&nbsp<a class="fa fa-sort fa-fw" href="<?php echo $this->url(array(), 'warehouse_sort_type'); ?>"></a></th>
                                <th>Дата&nbsp<a class="fa fa-sort fa-fw" href="<?php echo $this->url(array(), 'warehouse_sort_date'); ?>"></a></th>
                                <th>Прайс&nbsp<a class="fa fa-sort fa-fw" href="<?php echo $this->url(array(), 'warehouse_sort_remain'); ?>"></a></th>
                                <th>Остаток&nbsp<a class="fa fa-sort fa-fw" href="<?php echo $this->url(array(), 'warehouse_sort_remain'); ?>"></a></th>
                        <th><center><abbr title="Редактировать"><i class="fa fa-gavel fa-fw"></i></center></th>
                        <th><center><abbr title="Удалить"><i class="fa fa-trash-o fa-fw"></i></center></th>

                        </tr>
                        
                         </thead>
                        <tbody>
                        <?php
                        foreach ($this->warehouse as $rows) {
                            ?> <tr class="gradeA">
                                <td><p><img id='war_img' src="/img/<?php echo $this->escape($rows['path']); ?>" width='50' height='50'></p></td>
                                <td><?php echo $this->escape($rows['serial']); ?></td>
                                <td><?php echo $this->escape($rows['name']); ?></td>
                                <td><?php echo $this->escape($rows['type']); ?></td>
                                <td><?php echo $this->escape($rows['lastadding']); ?></td>
                                <td><center><?php echo $this->escape($rows['price']); ?> грн</center></td>
                                <td><center><?php echo $this->escape($rows['remain']); ?></center></td>
                                <td><center><a class="fa fa-gavel fa-fw" href="/warehouse/edit/id/<?= $this->escape($rows['id']) ?>"></a></center></td>
                                <td><center><a class="fa fa-trash-o fa-fw" href="/warehouse/delete/id/<?= $this->escape($rows['id']) ?>"></a></center></td>
                            </tr> <? } ?>                            

                        </tbody>
                    </table>
                    <table width=100% border="0">       
                        <tr>
                            <td align="left">
                                Показано от <?=$this->page_first?> до <?=$this->page_last?> из <?=$this->count?> записей
                            </td>
                            <td align="right">
                                <ul class="pagination">
                                    <li class="paginate_button previous <?=$this->previos_page?>" aria-controls="dataTables-example" tabindex="0" id="dataTables-example_previous">
                                        <a href="/warehouse/index/sort/<?=$_SESSION['sort']?>/page/<? if($_SESSION['page']>1) { echo ($_SESSION['page']-1); } else { echo ($_SESSION['page']); } ?><?=$this->search_param?>">назад</a>
                                    </li>
                                    
                                    <? foreach ($this->button_parameters as $key) { ?>
                                    <li class="paginate_button <?=$key['active']?>" aria-controls="dataTables-example" tabindex="0">
                                        <a href="/warehouse/index/sort/<?=$_SESSION['sort']?>/page/<?=$key['number']?><?=$this->search_param?>"><?=$key['number']?></a>
                                    </li> <? } ?>

                                    
                                    <li class="paginate_button next <?=$this->next_page?>" aria-controls="dataTables-example" tabindex="0" id="dataTables-example_next">
                                        <a href="/warehouse/index/sort/<?=$_SESSION['sort']?>/page/<?=$this->last_page?><?=$this->search_param?>">Next</a>
                                    </li>
                                </ul>
                            </td>
                        </tr>
                    </table>
                </div>
                <!-- /.table-responsive -->
                <div class="well">
                    <h4>Информация каталога</h4>
                    <p>Выборка : <?=$_SESSION['select_limit'];?> |
                       Текущая страница : <?=$_SESSION['page'];?> |
                       Сортировка : <?=$_SESSION['sort'];?> |
                       Всего в базе : <?=$this->count;?>
                    </p>
                </div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>

