<?php $this->headTitle('Выдача запчастей'); ?>
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header" id='test_js'><i class="fa fa-edit fa-fw"></i> Выдача запчастей</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<form id="form_spares" name="form_spares" method="post">
    <div class="main_spares_block">
        <div class="left_spares_block">
            <div id="spares_block">
                <p>Получатель</p>
                <input class="form-control <?=$this->error['recipient'] ?>" placeholder="введите получателя" name="recipient" type="input" value="<?=$this->recipient; ?>">
            </div>
        </div>
        <div class="right_spares_block">
            <div id="spares_block">
                <p>Комментарий</p>
                <input  class="form-control <?=$this->error['comments'] ?>" placeholder="введите комментарий" name="comments" type="input" value="<?=$this->comments; ?>">
            </div>
        </div>
    </div>
    <p class="<?=$this->error_message?> message_in ">Необходимо заполнить все поля. Ввод только на русском языке.Если поле не используется ставте пометку 'Нет'</p>
    <br>
    <button form="form_spares" class="btn btn-lg btn-success btn-block" type="submit">Выгрузить запчасти</button>
    <br>
    
    <div class="panel-body">
        <div class="dataTable_wrapper">
            <table width=100% class="table table-striped table-bordered table-hover" id="dataTables-example">
                <thead>
                    <tr>
                        <th>Фото</th>
                        <th>Серийный номер</th>
                        <th>Название</th>
                        <th>Остаток</th>
                        <th>К-во</th>
                        <th>CH</th>
                    </tr>
                </thead>
                <tbody>

                <?php
                 foreach ($this->warehouse as $rows) {

                ?><tr id='spares_row' class="gradeA">
                        <td id="spares_foto"><p><img src="/img/<?php echo $this->escape($rows['path']); ?>" width="30px" height="30px" ></p></td>
                        <td><?php echo $this->escape($rows['serial']); ?></td>
                        <td><?php echo $this->escape($rows['name']); ?></td>
                        <td id="spares_remain"><center><?php echo $this->escape($rows['remain']); ?></center></td>
                        <td id="spares_remain_check" >
                            <input class="check_spare_<?php echo $this->escape($rows['id']); ?> form-control <?=$this->error["{$this->escape($rows['id'])}"]; ?>" 
                                   <? if(!$this->checked["{$this->escape($rows['id'])}"]) { echo ('disabled'); }?> 
                                   name="<?php echo $this->escape($rows['id']); ?>" 
                                   type="input" 
                                   value="<?=$this->check_data["{$this->escape($rows['id'])}"];?>">
                        </td>
                        <td id="spares_check">
                            <input class="spare_check spare_check_<?php echo $this->escape($rows['id']); ?> "
                                   name="check_<?php echo $this->escape($rows['id']); ?>" type="checkbox" 
                                   value="<?php echo $this->escape($rows['id']); ?>" <?=$this->checked["{$this->escape($rows['id'])}"];?> 
                                   <? if($rows['remain']<1){echo ('disabled'); } ?>>
                        </td>
                    </tr> <? } ?>                            

                </tbody>
            </table>
        </div>
        <br>
        <button form="form_spares" class="btn btn-lg btn-success btn-block" type="submit">Выгрузить запчасти</button>
        <br>
    </div>
</form>