<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><i class="fa fa-thumb-tack fa-fw"></i> История изменений</h1>
        <h4>Аппарат: <b><?php echo $this->escape($this->history[0]['name']); ?></b></h4>
        <h4>Серийный номер: <b><?php echo $this->escape($this->history[0]['number']); ?></b></h4>
    </div>
    <!-- /.col-lg-12 -->
</div>	
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class='row'>
                   
                    <div class="col-sm-12">
                        <div class="dataTables_length" id="dataTables-example_length">
                            <button type="button" onclick="window.location.href = '/catalog/index/'" class="btn btn-default history_but">Назад</button>
                            <div class="history_data"><h5>Внесен в базу: <b><?php echo $this->escape($this->history[0]['data']); ?></b></h5></div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="dataTable_wrapper">
                    <table width=100% class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                            <tr>
                                <th>Дата изменения&nbsp</th>
                                <th>Принадлежность&nbsp</th>
                                <th>Территория&nbsp</th>
                                <th>Статус&nbsp</th>
                        </tr>
                        
                         </thead>
                        <tbody>

                        <?php
                        foreach ($this->history as $rows) {
                            ?> <tr class="gradeA">
                                <td><?php echo $this->escape($rows['data']); ?></td>
                                <td><?php echo $this->escape($rows['owner']); ?></td>
                                <td><?php echo $this->escape($rows['user']); ?></td>
                                <td><?php echo $this->escape($rows['status']); ?></td>
                            </tr> <? } ?>                            

                        </tbody>
                    </table>
                </div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>

