<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Пользователи</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>	
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class='row'>
                      <div class="col-sm-4">
                        <div class="dataTables_length" id="dataTables-example_length">
                            <button type="button" onclick="window.location.href = '/setup/addaccess/'" class="btn btn-default">Добавить</button>
                            <button type="button" onclick="window.location.href = '/setup/access/'" class="btn btn-default">Обновить</button>
                        </div>
                        </div>
                </div>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="dataTable_wrapper">
                    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                            <tr>
                                <th>Пользователь&nbsp</th>
                                <th>Пароль&nbsp</th>
                                <th>Роль&nbsp</th>
                                <th><center><i class="fa fa-wrench fa-fw"></i></center></th>
                                <th><center><i class="fa fa-trash-o fa-fw"></i></center></th>

                            </tr>
                        </thead>
                        <tbody>

                            <?php
                            foreach ($this->users as $rows) { if($rows['id']!=1){
                            ?> <tr class="gradeA">
                                    <td><?php echo $this->escape($rows['username']); ?></td>
                                    <td><?php echo $this->escape($rows['password']); ?></td>
                                    <td><?php echo $this->escape($rows['role']); ?></td>
                                    <td><center><a class="fa fa-wrench fa-fw" href="/setup/editaccess/id/<? echo $this->escape($rows['id'])?>"></a></center></td>
                                    <td><center><a class="fa fa-trash-o fa-fw" href="/setup/deleteaccess/id/<? echo $this->escape($rows['id'])?>"></a></center></td>
                            </tr> <? }} ?>                            



                        </tbody>
                    </table>
                </div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>

