<?php
// Создаём заголовок страницы, который загрузится в layout
$this->title = "Удаление записи";

$this->headTitle($this->title);
?>

<div class="row">
    <div class="col-lg-12">
        <h3 class="page-header">Удаление записи</h3>

    </div>
    <!-- /.col-lg-12 -->
</div>
<div class="well">
    <h4>Вы действительно хотите удалить запись?</h4>
    
    <h4>Запись:&nbsp;<?php echo($this->data['user']); ?></h4>
   
 <? echo $this->form; ?>  
    <br>
    <h4><font color="red">Внимание! ВCE данные с текущей территорией будут УДАЛЕНЫ!</font></h4>
    <p>(При удалении текущей записи все связанные с ней данные удалятся автоматически) </p>
</div>

