<?php
// Создаём заголовок страницы, который загрузится в layout
$this->title = "Удаление записи";

$this->headTitle($this->title);
?>

<div class="row">
    <div class="col-lg-12">
        <h3 class="page-header">Удаление пользователя</h3>

    </div>
    <!-- /.col-lg-12 -->
</div>
<div class="well">
    <h4>Вы действительно хотите удалить пользователя?</h4>
    <h4>Пользователь:&nbsp;<? echo $this->access['username']?></h4>
   
 <? echo $this->form; ?>  
    <br>
</div>

