<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Настройки базы данных</h1>

    </div>
    <!-- /.col-lg-12 -->
</div>	
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
            <p>Настройки каталога</p>
            <li>
                <a href="<?php echo $this->url(array(), 'setup_names'); ?>"><i class="fa fa-dashboard fa-fw"></i> Названия аппаратов</a>
            </li>
            <li>
                <a href="<?php echo $this->url(array(), 'setup_owners'); ?>"><i class="fa fa-table fa-fw"></i> Принадлежность</a>
            </li>
            <li>
                <a href="<?php echo $this->url(array(), 'setup_users'); ?>"><i class="fa fa-edit fa-fw"></i> Территория использования</a>
            </li>
            <li>
                <a href="<?php echo $this->url(array(), 'setup_status'); ?>"><i class="fa fa-edit fa-fw"></i> Статус</a>
            </li>
            <p>Настройки документации</p>
            <li>
                <a href="<?php echo $this->url(array(), 'setup_access'); ?>"><i class="fa fa-edit fa-fw"></i> Документация</a>
            </li>
            <p>Настройки доступа</p>
            <li>
                <a href="<?php echo $this->url(array(), 'setup_access'); ?>"><i class="fa fa-edit fa-fw"></i> Доступ</a>
            </li>
        </ul>
    </div>
    <!-- /.sidebar-collapse -->
