<div class="row">
    <div class="col-lg-12">
        <h3 class="page-header">Пользователи аппаратов</h3>

    </div>
    <!-- /.col-lg-12 -->
</div>
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="dataTables_length" id="dataTables-example_length">
            <button type="button" onclick="window.location.href = '/setup/index/'" class="btn btn-default">Назад</button>
            <button type="button" onclick="window.location.href = '/setup/adduser/'"class="btn btn-default">Добавить</button>
        </div>
    </div>
    <div class="panel-body">
        <div class="dataTable_wrapper">
            <table width=100% class="table table-striped table-bordered table-hover" id="dataTables-example">
                <? foreach ($this->users as $value) { ?>
                    <tr>
                        <td><?= $this->escape($value['user']) ?></td>
                        <td width="50px"><a href="/setup/edituser/id/<?=$this->escape($value['id']);?>">Ред.</a></td>
                        <td width="50px"><a href="/setup/deleteuser/id/<?=$this->escape($value['id']);?>">Уд.</a></td>
                    </tr>
                <? } ?>
            </table>
        </div>
    </div>
</div>
