<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><i class="fa fa-dashboard fa-fw"></i> Торговые точки</h1>

    </div>
    <!-- /.col-lg-12 -->
</div>	

<!--<center><div id="map_canvas" style="width:90%; height:500px;" ></div></center>-->
<br>
<input id="address" value="Киев, Золотые ворота" type="hidden">

<center><div style=" width: 90%; height: 500px;" id="map_canvas"></div></center>
<br>
<br>
<br>

