<?php
// Создаём meta тег Content-Type
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=win-1251');
// Указываем символ разделитель в теге title
$this->headTitle()->setSeparator(' - ');
// Определяем содержимое тега title
$this->headTitle('SB Coffee Service Center Admin');
// Выводим doctype, который считывается из application.ini
echo $this->doctype();
echo $this->headTitle();
?>
<html lang="en">

    <head>

        <title>Second layout</title>

        <!-- Bootstrap Core CSS -->
        <link href="/css/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">

        <!-- MetisMenu CSS -->
        <link href="/css/bower_components/metisMenu/dist/metisMenu.min.css" rel="stylesheet">

        <!-- Timeline CSS -->
        <link href="/css/dist/css/timeline.css" rel="stylesheet">

        <!-- Custom CSS -->
        <link href="/css/dist/css/sb-admin-2.css" rel="stylesheet">

        <!-- Morris Charts CSS -->
        <link href="/css/bower_components/morrisjs/morris.css" rel="stylesheet">
        <link href="/css/style.css" rel="stylesheet">

        <!-- Custom Fonts -->
        <link href="/css/bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

   </head>

<body>
    
    <?php echo $this->layout()->content; ?>


    <!-- jQuery -->
    <script src="../bower_components/jquery/dist/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="../bower_components/bootstrap/dist/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="../bower_components/metisMenu/dist/metisMenu.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="../dist/js/sb-admin-2.js"></script>

</body>

</html>


</html>
