<?php
//$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf8');
//$this->headTitle()->setSeparator(' - ');
//$this->headTitle('SB Coffee Service Center Admin');
// echo $this->doctype();
?>

<!DOCTYPE html>
<html>
    <head>
        <?php
        //echo $this->headMeta();
        //echo $this->headTitle();
        ?>
        <meta name="viewport" content="initial-scale=1.0">
        <meta charset="cp1251">

        <link rel="shortcut icon" href="/img/icon.png">
        <!--Bootstrap Core CSS--> 
        <link href="/css/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">

        <!--MetisMenu CSS--> 
        <link href="/css/bower_components/metisMenu/dist/metisMenu.min.css" rel="stylesheet">

        <!--Timeline CSS--> 
        <link href="/css/dist/css/timeline.css" rel="stylesheet">

        <!--Custom CSS--> 
        <link href="/css/dist/css/sb-admin-2.css" rel="stylesheet">

        <!--Morris Charts CSS--> 
        <link href="/css/bower_components/morrisjs/morris.css" rel="stylesheet">

        <!--Custom Fonts--> 
        <link href="/css/bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        <link href="/css/style.css" rel="stylesheet">


        <script src="//ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="js/script.js"></script>



        <!-- google maps init -->
        <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
        <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
        <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false" ></script>

        <script type="text/javascript">
            var geocoder;
            var map;
            var address = 'Киев, Воскресенская 14а';
            function initialize() {
                geocoder = new google.maps.Geocoder();
                var latlng = new google.maps.LatLng(-34.397, 150.644);
                var myOptions = {
                    zoom: 11,
                    center: latlng,
                    mapTypeControl: true,
                    mapTypeControlOptions: {
                        style: google.maps.MapTypeControlStyle.DROPDOWN_MENU
                    },
                    navigationControl: true,
                    mapTypeId: google.maps.MapTypeId.ROADMAP
                };

                map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);

                if (geocoder) {
                    geocoder.geocode({
                        'address': address
                    }, function (results, status) {
                        if (status == google.maps.GeocoderStatus.OK) {
                            if (status != google.maps.GeocoderStatus.ZERO_RESULTS) {
                                map.setCenter(results[0].geometry.location);

                                //???? ????
                                var infowindow = new google.maps.InfoWindow({
                                    content: '<b>' + address + '</b>' + '<p>S/N:APN345 TreviChiara</p>',
                                    size: new google.maps.Size(150, 50)
                                });

                                //
                                var marker = new google.maps.Marker({
                                    position: results[0].geometry.location,
                                    map: map,
                                    title: address
                                });

                                //
                                google.maps.event.addListener(marker, 'click', function () {
                                    infowindow.open(map, marker);
                                });

                            } else {
                                alert("No results found");
                            }
                        } else {
                            alert("Geocode was not successful for the following reason: " + status);
                        }
                    });
                }

                address2 = 'Киев, ул.Милютенко 17';

                if (geocoder) {
                    geocoder.geocode({
                        'address': address2
                    }, function (results, status) {
                        if (status == google.maps.GeocoderStatus.OK) {
                            if (status != google.maps.GeocoderStatus.ZERO_RESULTS) {
                                map.setCenter(results[0].geometry.location);

                                //???? ????
                                var infowindow = new google.maps.InfoWindow({
                                    content: '<b>' + address2 + '</b>' + '<p>S/N:APN245 VienaSuperavtomatika</p>',
                                    size: new google.maps.Size(150, 50)
                                });

                                //
                                var marker = new google.maps.Marker({
                                    position: results[0].geometry.location,
                                    map: map,
                                    title: address2
                                });

                                //
                                google.maps.event.addListener(marker, 'click', function () {
                                    infowindow.open(map, marker);
                                });

                            } else {
                                alert("No results found");
                            }
                        } else {
                            alert("Geocode was not successful for the following reason: " + status);
                        }
                    });
                }
            }
            google.maps.event.addDomListener(window, 'load', initialize);

        </script>



    </head>

    <body>
        <div id="wrapper">

            <!-- Navigation -->
            <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <a class="navbar-brand" href="/">Coffee Service Center Admin v2.4 11.2016&nbsp&nbsp&nbsp&nbspAromoPlyus POLTAVA department</a>
                </div>
                <ul class="nav navbar-top-links navbar-right">
                    <li class="dropdown">
                        <a class="dropdown-toggle" href="/access/logout/" data-toggle="dropdown" href="#">
                            <i class="fa fa-power-off fa-fw"></i>  <i class="fa fa-caret-down"></i>
                        </a>
                    </li>
                </ul>
                <!-- /.navbar-top-links -->
                <div class="navbar-default sidebar" role="navigation">
                    <div class="sidebar-nav navbar-collapse">
                        <ul class="nav" id="side-menu">
                            <li class="sidebar-search">
                                <div class="input-group custom-search-form">
                                    <input type="text" class="form-control" placeholder="Search...">
                                    <span class="input-group-btn">
                                        <button class="btn btn-default" type="button">
                                            <i class="fa fa-search"></i>
                                        </button>
                                    </span>
                                </div>
                                <!-- /input-group -->
                            </li>
                            <li>
                                <a href="<?php echo $this->url(array(), 'catalog'); ?>"><i class="fa fa-dashboard fa-fw"></i> Каталог аппраратов</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url(array(), 'repairs_stat'); ?>"><i class="fa fa-wrench fa-fw"></i> История ремонтов</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url(array(), 'outlets'); ?>"><i class="fa fa-shopping-cart"></i> Торговые точки</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url(array(), 'sales'); ?>"><i class="fa fa-euro fa-fw"></i> Продажа аппаратов</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url(array(), 'service'); ?>"><i class="fa fa-cog fa-fw"></i> Услуги мастерской</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url(array(), 'warehouse'); ?>"><i class="fa fa-edit fa-fw"></i> Склад запчастей</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url(array(), 'statistic'); ?>"><i class="fa  fa-bar-chart-o fa-fw"></i> Статистика</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url(array(), 'documentation'); ?>"><i class="fa  fa-book fa-fw"></i> Документация</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url(array(), 'reports'); ?>"><i class="fa  fa-tags"></i> Отчеты .xls</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url(array(), 'setup'); ?>"><i class="fa fa-magic fa-fw"></i> Настройки</a>
                            </li>
                        </ul>
                    </div>
                    <!-- /.sidebar-collapse -->
                </div>
                <!-- /.navbar-static-side -->
            </nav>
            <div id="page-wrapper">

                <?php echo $this->layout()->content; ?>

            </div>
        </div>
        <!-- /#wrapper -->
    </body>

</html>
