<?php
// Создаём заголовок страницы, который загрузится в layout
$this->title = "Добавление ремонта";

$this->headTitle($this->title);
?>

<br>
<br>
<div class="well">
    <h4>Вы действительно хотите удалить запись?</h4>
    
    <p>Номер аппарата:<?php echo($this->device['number']); ?><br>
       Номер аппарата:<?php echo($this->device['name']); ?><br>
       Номер аппарата:<?php echo($this->device['status']); ?><br>
    </p>
   
 <? echo $this->form; ?>  
    <br>
    <p>Внимание! Все данные включая ремонты будут удалены!</p>
</div>
