<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><i class="fa fa-dashboard fa-fw"></i> Каталог аппаратов</h1>

    </div>
    <!-- /.col-lg-12 -->
</div>	
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <table width=100% border="0">
                    <tr  align="center">
                        <td width="30%" align="left">
                        <div class="dataTables_length" id="dataTables-example_length">
                            <form id="form_select" name="form_select" method="post">
                                Показать 

                                <select name="select_limit" onchange="form_select.submit();">

                                    <option <? if($_SESSION['select_limit']== 10) {echo('selected ');} ?>value="10">10</option>
                                    <option <? if($_SESSION['select_limit']== 25) {echo('selected ');} ?>value="25">25</option>
                                    <option <? if($_SESSION['select_limit']== 50) {echo('selected ');} ?>value="50">50</option>
                                    <option <? if($_SESSION['select_limit']== 100) {echo('selected ');} ?>value="100">100</option>
                                    <option <? if($_SESSION['select_limit']== 99999) {echo('selected ');} ?>value="99999">все</option>
                                </select>
                                
                                <input name="search_catalog" type="hidden" value="<?=$this->search?>" >

                                Фильтр
                                
                                <select name="select_type" onchange="form_select.submit();">

                                    <option <? if($_SESSION['select_type']== 'all') {echo('selected ');} ?>value="all">Все</option>
                                <?php foreach ($this->types as $key=>$value) { ?>
                                   
                                    <option <? if($_SESSION['select_type']== $value) {echo('selected ');} ?>value="<?=$value?>"><?=$value?></option>
                                    
                                <? } ?>
       
                                </select>
                            </form>
                        </div>
                    </td>
                   <td align="center">
                        <div class="dataTables_length" id="dataTables-example_length" >
                            <button type="button" onclick="window.location.href = '/catalog/add/'" class="btn btn-default">Добавить</button>
                            <button type="button" onclick="window.location.href = '/catalog/index/select_type/all/page/1'"class="btn btn-default">Обновить</button>
                            <button type="button" onclick="window.location.href = '/catalog/toexcel/'" class="btn btn-default">To Excel</button>
                        </div>
                    </td>
                    <td  width="30%" align="right">
                        <div class="dataTables_length" id="dataTables-example_length">
                            <form id="search_form" method="post">
                            <div class="input-group custom-search-form">
                                <input name="search_catalog" type="text" value="<?=$this->search?>" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                    <button form="search_form" class="btn btn-default" type="submit">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                            </form>
                        </div>
                    </td>
                    </tr>
                </table>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="dataTable_wrapper">
                    <table  cellpadding="10" width=100% class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                            <tr>
                                <th><center><abbr title="Торговая точка"><i class="fa fa-shopping-cart"></i></abbr></center></th>
                                <th>Номер&nbsp<a class="fa fa-sort fa-fw" href="<?php echo $this->url(array(), 'catalog_sort_number'); ?>"></a></th>
                                <th>Название&nbsp<a class="fa fa-sort fa-fw" href="<?php echo $this->url(array(), 'catalog_sort_name'); ?>"></a></th>
                                <th>Принадлежность&nbsp<a class="fa fa-sort fa-fw" href="<?php echo $this->url(array(), 'catalog_sort_owner'); ?>"></a></th>
                                <th>Территория&nbsp<a class="fa fa-sort fa-fw" href="<?php echo $this->url(array(), 'catalog_sort_user'); ?>"></a></th>
                                <th>Статус&nbsp<a class="fa fa-sort fa-fw" href="<?php echo $this->url(array(), 'catalog_sort_status'); ?>"></a></th>
                               <!-- <th>Торговая точка&nbsp</th> -->
                                <th><center><abbr title="Ремонты"><i class="fa fa-wrench fa-fw"></i></abbr></center></th>
                                <th><center><abbr title="История"><i class="fa fa-thumb-tack fa-fw"></i></abbr></center></th>
                                <th><center><abbr title="Редактировать"><i class="fa fa-gavel fa-fw"></i></abbr></center></th>
                                <th><center><abbr title="Удалить"><i class="fa fa-trash-o fa-fw"></i></abbr></center></th>

                        </tr>
                        
                         </thead>
                        <tbody>

                        <?php
                        foreach ($this->devices as $rows) {
                            ?> <tr class="gradeA row_set">
                                <td><center><a class="shop support-hover fa fa-shopping-cart " id='<?php echo $this->escape($rows['id']); ?>'></a></center></td>
                                <td><?php echo $this->escape($rows['number']); ?></td>
                                <td><?php echo $this->escape($rows['name']); ?></td>
                                <td><?php echo $this->escape($rows['owner']); ?></td>
                                <td><?php echo $this->escape($rows['user']); ?></td>
                                <td><?php echo $this->escape($rows['status']); ?></td>
                                <td><center><a class="fa fa-wrench fa-fw" href="/repairs/index/number/<?= $this->escape($rows['number']) ?>"></a></center></td>
                                <td><center><a class="fa fa-thumb-tack fa-fw" href="/history/index/number/<?= $this->escape($rows['number']) ?>"></a></center></td>
                                <td><center><a class="fa fa-gavel fa-fw" href="/catalog/edit/id/<?= $this->escape($rows['id']) ?>"></a></center></td>
                                <td><center><a class="fa fa-trash-o fa-fw" href="/catalog/delete/id/<?= $this->escape($rows['id']) ?>"></a></center></td>
                            </tr>
                            <tr  class="row_set_<?= $this->escape($rows['id']) ?> shop_table ">
                                <th colspan="10"></th>
                            </tr>
                            <tr  class="row_set_<?= $this->escape($rows['id']) ?> shop_table">
                                <th rowspan="7"></th>
                                <th><i class="fa fa-road"></i>&nbsp;город</th>
                                <td  colspan="7"><?php echo $this->escape($rows['city']); ?></td>
                            </tr>
                            <tr  class="row_set_<?= $this->escape($rows['id']) ?> shop_table">
                                <th><i class="fa fa-home"></i>&nbsp;адрес</th>
                                <td colspan="7"><?php echo $this->escape($rows['adress']); ?></td>
                            </tr>
                            <tr  class="row_set_<?= $this->escape($rows['id']) ?> shop_table">
                                <th><i class="fa fa-pencil-square "></i>&nbsp;название ТТ</th>
                                <td colspan="7"><?php echo $this->escape($rows['tt_name']); ?></td>
                            </tr>
                            <tr  class="row_set_<?= $this->escape($rows['id']) ?> shop_table">
                                <th><i class="fa fa-user"></i>&nbsp;контактные данные</th>
                                <td colspan="7"><?php echo $this->escape($rows['tt_user']); ?></td>
                            </tr>
                            <tr class="row_set_<?= $this->escape($rows['id']) ?> shop_table">
                                <th><i class="fa fa-phone-square"></i>&nbsp;номер договора</th>
                                <td colspan="7"><?php echo $this->escape($rows['tt_phone']); ?></td>
                            </tr>
                            <tr class="row_set_<?= $this->escape($rows['id']) ?> shop_table">
                                <th><i class="fa fa-map-marker  "></i>&nbsp;координаты</th>
                                <td colspan="7">
                                    <div id="cord_<?= $this->escape($rows['id']) ?>">
                                        <span id="cordsp_<?= $this->escape($rows['id']) ?>">
                                            <b>Долгота: </b><?php echo $this->escape($rows['lat']);?>
                                            <b>Широта: </b><?php echo $this->escape($rows['lng']);?>
                                        </span>
                                    </div>
                                </td>
                            </tr>
                            <tr class="row_set_<?= $this->escape($rows['id']) ?> shop_table">
                                <td colspan="8">
                                    <input type="checkbox" name="option2" value="a2">&nbsp;<b>Отображать на карте</b>  
                                    <b>&nbsp;&nbsp;&nbsp;Цвет метки:</b> 
                                    <input name="color" type="radio" value="red" checked=""> Красный
                                    <input name="color" type="radio" value="green"> Зеленый
                                    <input name="color" type="radio" value="blue" > Синий
                                    <input name="color" type="radio" value="yellow" > Желтый
                                    &nbsp;&nbsp;
                                    <button type="button" onclick="window.location.href = '/catalog/add/'" class="btn btn-default">На карту</button>
                                    <b>Координаты</b>&nbsp;
                                    <button type="button" value="<?php echo $this->escape($rows['id']);?>" class="autofind btn btn-default">Авто</button>
                                    <button type="button" value="<?php echo $this->escape($rows['id']);?>" class="manual   btn btn-default ">Ручн</button>
                                </td>
                            </tr>
                            <tr  class="row_set_<?= $this->escape($rows['id']) ?> shop_table">
                                <th colspan="10" ><center><i class="fa  fa-chevron-up"></i></center></th>
                            </tr>
                                <? } ?>                            

                        </tbody>
                    </table>
                    <table width=100% border="0">       
                        <tr>
                            <td align="left">
                                Показано от <?=$this->page_first?> до <?=$this->page_last?> из <?=$this->count?> записей
                            </td>
                            <td align="right">
                                <ul class="pagination">
                                    <li class="paginate_button previous <?=$this->previos_page?>" aria-controls="dataTables-example" tabindex="0" id="dataTables-example_previous">
                                        <a href="/catalog/index/sort/<?=$_SESSION['sort']?>/page/<? if($_SESSION['page']>1) { echo ($_SESSION['page']-1); } else { echo ($_SESSION['page']); } ?><?=$this->search_param?>">назад</a>
                                    </li>
                                    
                                    <? foreach ($this->button_parameters as $key) { ?>
                                    <li class="paginate_button <?=$key['active']?>" aria-controls="dataTables-example" tabindex="0">
                                        <a href="/catalog/index/sort/<?=$_SESSION['sort']?>/page/<?=$key['number']?><?=$this->search_param?>"><?=$key['number']?></a>
                                    </li> <? } ?>

                                    
                                    <li class="paginate_button next <?=$this->next_page?>" aria-controls="dataTables-example" tabindex="0" id="dataTables-example_next">
                                        <a href="/catalog/index/sort/<?=$_SESSION['sort']?>/page/<?=$this->last_page?><?=$this->search_param?>">вперед</a>
                                    </li>
                                </ul>
                            </td>
                        </tr>
                    </table>
                </div>
                <!-- /.table-responsive -->
                <div class="well">
                    <h4>Информация каталога</h4>
                    <p>Выборка : <? if($_SESSION['select_limit']!=99999) {
                       echo $_SESSION['select_limit'];
                    } else {
                        echo ("Все записи");
                    };?> |
                       Тип : <?=$_SESSION['select_type'];?> |
                       Текущая страница : <?=$_SESSION['page'];?> |
                       Сортировка : <?=$_SESSION['sort'];?> |
                       Всего в базе : <?=$this->count;?>
                    </p>
                    
                </div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>

