<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><i class="fa fa-tags"></i> Отчеты</h1>

    </div>
    <!-- /.col-lg-12 -->
</div>	
<div>
    <h4 class="fa fa-file-excel-o"> Выгрузка данных в MS Excel (.xls)</h4>
</div>
<br>
<div>
    <table width=100% class="table table-striped table-bordered table-hover" id="dataTables-example">
        <tr>
            <th><div><button type="button" onclick="window.location.href = '/catalog/toexcel/'" class="btn btn-default">Сохранить</button>
            &nbsp;&nbsp;&nbsp;&nbsp;Каталог аппаратов</div></th>
        </tr>
        <tr>
            <th><div><button type="button" onclick="window.location.href = '/repairs/toexcel/'" class="btn btn-default">Сохранить</button>
            &nbsp;&nbsp;&nbsp;&nbspВыписка всех ремонтов</div></th>
        </tr>
        <tr>
            <th><div><button type="button" onclick="window.location.href = '/warehouse/toexcel/'"class="btn btn-default">Сохранить</button>
            &nbsp;&nbsp;&nbsp;&nbsp;Склад запчастей</div></th>
        </tr>
        <tr>
            <th><div><button type="button" onclick="window.location.href = '/sales/toexcel/'"class="btn btn-default">Сохранить</button>
            &nbsp;&nbsp;&nbsp;&nbsp;Проданные аппараты</div></th>
        </tr>
        <tr>
            <th><div><button type="button" onclick="window.location.href = '/service/toexcel/'"class="btn btn-default">Сохранить</button>
            &nbsp;&nbsp;&nbsp;&nbsp;Услуги мастерской</div></th>
        </tr>
    </table>
</div>
