<?php global $settings; ?>
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><i class="fa fa-gears"></i> Добавить/Обновить базу данных</h1>

    </div>
    <!-- /.col-lg-12 -->
</div>	
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4>Версия программы: <b><?=$settings['lversion'];?></b></h4></center>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="dataTable_wrapper">
                    <table width=100% class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                            <tr>
                                <th><center>Выполнить действие</center></th>
                        <th><center><i class="fa fa-gears"></i></center></th>

                        </tr>

                        </thead>
                        <tbody>
                            <tr>
                                <td><center>Создать новую базу данных</center></td>
                                <td><center><button type="button" onclick="window.location.href = '/update/make/'" class="btn btn-primary">&nbsp;Создать&nbsp; </button></center></td>
                            </tr>                            
                            <tr>
                                <td><center>Загрузить начальные данные</center></td>
                                <td><center><button type="button" onclick="window.location.href = '/update/load/'" class="btn btn-primary">Загрузить</button></center></td>
                            </tr>                            
                            <tr>
                                <td><center>Обновить базу данных</center></td>
                                <td><center><button type="button" onclick="window.location.href = '/update/update/'" class="btn btn-primary">Обновить</button></center></td>
                            </tr>                            
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>

